### ISSUE TITLE
fastMeanFilter error

### ISSUE THREAD

**Issue by tarak77** [MonkeyLB/hicrep#64]
Hey man,
I was able to install hicrep from source and it works fine when h=0. But for nonzero values of h I get the following error:
```
Error in fastMeanFilter(as.matrix(mat1), h) : 
  could not find function "fastMeanFilter"
```

Any help?

**Comment by TaoYang-dev** [comment]
Could you please let me know which function gives you this error, get.scc()?

**Comment by TaoYang-dev** [comment]
Could you please let me know which function gives you this error, get.scc()?

**Comment by TaoYang-dev** [comment]
Could you please let me know which function gives you this error, get.scc()?

**Comment by TaoYang-dev** [comment]
Could you please let me know which function gives you this error, get.scc()?

**Comment by TaoYang-dev** [comment]
Could you please let me know which function gives you this error, get.scc()?

**Comment by TaoYang-dev** [comment]
Could you please let me know which function gives you this error, get.scc()?

**Comment by tarak77** [comment]
Yes its get.scc()

**Comment by TaoYang-dev** [comment]
It seems to me your compiling wasn't successful. The fastmeanfilter()
was written in C++.
Can you try fast.mean.fitler() and see if it works?

**Comment by tarak77** [comment]
Yes fast.mean.filter() seems to work. But not with get.scc() ??

**Comment by tarak77** [comment]
I just replaced fastMeanFilter() with fast.mean.filter() in get.scc() function. It seems to work now. Thanks!
